### ISSUE TITLE
Overseerr Connection

### ISSUE THREAD

**Issue by JamsRepos** [ASK-ME-ABOUT-LOOM/purgeomatic#1]
Hey, I don't use overseerr. I see that it's an optional parameter, so i've commented it out of my .env. I am assuming that because it has defaults set, that's the reason why i'm getting my logs spammed by connection errors to overseerr? Is it possible to toggle this off so I only see log messages? Kinda hard to read my dry log.

**Comment by ASK-ME-ABOUT-LOOM** [comment]
Yeah, good catch! I've just updated the code on both `delete.tv.unwatched.py` and `delete.movies.unwatched.py` to only call the block of code that connects to Overseerr if the Overseerr API key is set. Make sure that variable is commented out or doesn't exist in your `.env`.
