### ISSUE TITLE
Matching on movie titles isn't reliable

### ISSUE THREAD

**Issue by adamk33n3r** [ASK-ME-ABOUT-LOOM/purgeomatic#10]
I've come across some issues matching on title exactly. I know you were dealing with title matching in #9 and touched on using tmdbids but decided against it. Would it be possible to have both? How do you get the tmdb id from tautulli anyway? I can't find any information in the docs :P 

Here's an example.
In Radarr: `Star Wars: The Last Jedi`
In Plex/Tautulli: `Star Wars: Episode VIII - The Last Jedi`

**Comment by ASK-ME-ABOUT-LOOM** [comment]
To pull the TMDB ID from Tautulli requires two API calls: the first is the [`get_library_media_info`](https://github.com/Tautulli/Tautulli/wiki/Tautulli-API-Reference#get_library_media_info) query which pulls all of the media items in a given library. One of the items in each record is the `rating_key`, which, although the name is confusing (to me, at least) it appears to be the unique ID Tautulli uses. You use the rating key to run a [`get_metadata`](https://github.com/Tautulli/Tautulli/wiki/Tautulli-API-Reference#get_metadata) query. One of the items returned in that response is a list of GUIDs, resembling:
```
"guids": [
        "imdb://tt12345678",
        "tmdb://123123",
        "tvdb://456456"
      ],
```

Unfortunately, on some items, the result is just:
```
"guids": [],
```

There doesn't seem to be any rhyme or reason for it, and I can't see a way to tell Tautulli, "hey, fill in the unique IDs for these items, please," which would essentially solve this whole problem.

I just did some digging and it looks like it pulls this info from Plex. I just refreshed the metadata in Plex for a movie that had no metadata, and now the GUIDs are showing up. It looks like regular Plex metadata refreshes might be a suggestion to put in the readme.

What seems like the most straightforward approach is to do an API call for the GUIDs and see if they exist. If they exist, we match based on that. If they don't, we match based on title. I'll see about getting this coded.

**Comment by ASK-ME-ABOUT-LOOM** [comment]
This should be fixed. I'm now doing lookups for the list of GUIDs in the Tautulli API, and if they exist, I'm matching on TMDB/TVDB ID instead of title. Should the query for the GUID list for a given media item return empty (`[]`), it falls back to the less-reliable title-based match rather than giving up altogether. 

*Please go into Plex and trigger a metadata refresh!* It appears that the list of GUIDs in Tautulli is sourced directly from Plex metadata.

**Comment by adamk33n3r** [comment]
Awesome, thanks for the quick response! :D
