### ISSUE TITLE
Possible to Use Tags

### ISSUE THREAD

**Issue by esmoyer** [ASK-ME-ABOUT-LOOM/purgeomatic#18]
Just discovered this on my journey to keep my library tidy. I have Overseerr tag requested movies accordingly and was wanting to see if this is able to look at and apply only to a specific tag? My brother requests a lot of old movies and TV shows that only he will watch so I have to manually clean those up all the time. I am trying to find a way to auto clean those up based on the tag "overseer" (or his username that overseer tags) and greater than 180 days. From what I can tell, this isn't currently possible without some tweaking, correct? Thanks!

**Comment by ASK-ME-ABOUT-LOOM** [comment]
Unfortunately, no, I don't support lookups of movies based on tag like that and I don't foresee adding that feature. 

It might save you some trouble to create a separate library for old movies. The general consensus online is that you could spin up separate overseerr & radarr containers which are configured to add movies into that library. If you do that, you can just run this script against the library and only those movies will be targeted.

**Comment by esmoyer** [comment]
I was actually able to figure this out and wrote a separate script to call. Thanks!
