### ISSUE TITLE
delete.movies.unwatched.py  list index out of range

### ISSUE THREAD

**Issue by xman0980** [ASK-ME-ABOUT-LOOM/purgeomatic#19]
ERROR: There was a problem connecting to Tautulli/Radarr/Overseerr. Please double-check that your connection settings and API keys are correct.

Error message:
list index out of range

The script runs for a while correctly, and then just crashes with that error. I increased the list TAUTULLI_NUM_ROWS=50000  but it doesn't seem to make a difference.  I tried refreshing all metadata for that library, and it still fails with that error.

**Comment by ASK-ME-ABOUT-LOOM** [comment]
I had been waiting for a report from #17 before pushing this most recent change, but I hadn't heard back. I believe the push I just made will fix this issue for you. Can you confirm? 

Edit: I should add that you should try refreshing your metadata in Plex.

In the Plex web UI, click the library, then the three-dot menu → manage library → refresh all metadata.

**Comment by xman0980** [comment]
I will run it in a bit and let you know. Currently running plex_dupefinder in case the dupes are causing issues. As soon as I can run it, I'll let you know.

Found 35 dupes for section 'Movies'
Found 10022 dupes for section 'TV Shows'
Found 30 dupes for section 'Kid Movies'
Found 2792 dupes for section 'Kid TV Shows'


Gonna take a bit. LOL


So far so good. It had an issue, but seems to keep on going without just crashing.

Its been running for 2.5 hours now. Haven't had it run this long without issue.


```DELETED: The Nutty Professor | Radarr ID: 3365 | TMDB ID: 9327
WARNING: Lifetime of Comedy: Unexpected GUID metadata from Tautulli. Please refresh your library's metadata in Plex. Using less-accurate 'search mode' for this title. Error message: list index out of range
DELETED: Life at the Top | Radarr ID: 39445 | TMDB ID: 118255```
