### ISSUE TITLE
Possible to clean multiple libraries at once or setup different .env configs

### ISSUE THREAD

**Issue by xman0980** [ASK-ME-ABOUT-LOOM/purgeomatic#20]
I love this script. Makes cleaning up my library easier. I have multiple libraries. Is there a way to have it clean multiple libraries at once? 
I don't know if its as simple as just putting the ID,ID,ID in the .env 
or is there a way to run it and have it reference a different env for each library?
My goal is to be able to set this as a cron job, and have it clean up my libraries once a week.

Thanks

**Comment by ASK-ME-ABOUT-LOOM** [comment]
While this script can't do multiple libraries in a single run, there's no reason you couldn't leave the section ID variable out of your .env file (or use a separate .env file just to be called with cron) and include the section ID for a library on the command line instead, e.g. `docker run --rm --env-file .env -e TAUTULLI_MOVIE_SECTIONID=14...` and so on. 

There's also nothing stopping you from running it concurrently with other runs of the script. By all means, cron them up at the exact same time if you like!

**Comment by xman0980** [comment]
Cool. I'll close this for now. If I have problems setting it up, I'll ask for some help. Thanks!
