### ISSUE TITLE
Support for multiple Radarr and Sonarr instances

### ISSUE THREAD

**Issue by qirk4** [ASK-ME-ABOUT-LOOM/purgeomatic#21]
Hi!
First, this is a godsend as I have tons of media downloaded, thank you!
I share my Plex servers with friends and family, but they are not tech-savvy, so I only allow them to download up to Full HD quality. But I allow myself to download 4K too.
I could only solve this by having 2 Radarr and Sonarr containers running. One for 4K, one for Full HD cutoff.

I want to prune all 4 of my libraries, but cannot really configure 2 Radarr and Sonarr instances in the .env file as the second one overwrites the first.

Do you plan to support multiple instances of the same type?

**Comment by ASK-ME-ABOUT-LOOM** [comment]
The script doesn't support multiple instances, but you can just use multiple `.env` files. Make another one and call it `.env4k` or something like that, then call the script using that instead. 

Good luck!

**Comment by qirk4** [comment]
Oh, thats great!
Thank you!
