### ISSUE TITLE
Size of every result while running?

### ISSUE THREAD

**Issue by palla89** [ASK-ME-ABOUT-LOOM/purgeomatic#23]
Hi! Amazing work!!
It would be great to know also the size of every result, it could be useful to decide if a movie should stay or not 😃 
something like:
DRY RUN: Ad astra | Radarr ID: 1087 | TMDB ID: 419704 |  9.38GB

Sorry if it's an unappropriate request 

Thank you!

**Comment by ASK-ME-ABOUT-LOOM** [comment]
Yeah, not a bad idea. This is done. 

I did it in a slightly different order, though. I ended up doing:

`Title | Size | Radarr | TMDB`
