### ISSUE TITLE
Make script check TMDB and the TVDB for ratings before deleting. 

### ISSUE THREAD

**Issue by Stewdawg69** [ASK-ME-ABOUT-LOOM/purgeomatic#24]
Hey! Firstly, The project looks awesome!

So, this isn't an issue, but not sure where else to ask this... is it possible to make this script have certain critera. E.g. Movies and/or tv series not watched in 12 months with a rating below 55% will be automatically deleted. 

This would be good as it'll just really clear out the junk. You could pretty safely just let that run on its own if setup correctly. 

Anyway, hope you like my idea. Keep up the good work!

**Comment by ASK-ME-ABOUT-LOOM** [comment]
I'm sure such a thing is possible, but it's really not what I've created this for. 

There's a more complicated projected called [Maintainerr](https://github.com/jorenn92/Maintainerr) which may do what you're looking for. I'm not trying to keep pace with something along those lines - I want something small that just removes content nobody is watching anyway.

**Comment by Stewdawg69** [comment]
Oh wow… thanks for the fast reply!

No problem at all. I’ll take a look at maintainerr!

Awesome work regardless!

**Comment by ASK-ME-ABOUT-LOOM** [comment]
#

**Comment by ASK-ME-ABOUT-LOOM** [comment]
#
