### ISSUE TITLE
Feature Request - Sonarr season deletion?

### ISSUE THREAD

**Issue by nebb00** [ASK-ME-ABOUT-LOOM/purgeomatic#3]
Just an idea. But could purge seasons of shows rather than the entire show? No reason keeping 30 seasons, if only the last 2 are being watched recently.

**Comment by ASK-ME-ABOUT-LOOM** [comment]
My issue with this is that seasons frequently get backfilled on shows (at least on my server) and it's much simpler to remove the show entirely when nobody is watching it after a reasonably long period of time.

**Comment by nebb00** [comment]
> My issue with this is that seasons frequently get backfilled on shows (at least on my server) and it's much simpler to remove the show entirely when nobody is watching it after a reasonably long period of time.

Suppose at least using tautulli. You can purge based on last viewed. Been X months since last viewed or not viewed. Purge

**Comment by ASK-ME-ABOUT-LOOM** [comment]
This will require an additional layer of logic, too: removing seasons after a period of time, then the entire show after another. Sorry, not on the radar.
