### ISSUE TITLE
issues in running in linux container

### ISSUE THREAD

**Issue by kysersoze81** [ASK-ME-ABOUT-LOOM/purgeomatic#4]
Issue:
```
/opt/purgeomatic# python3.9 ./delete.movies.unwatched.py 
DRY_RUN enabled!
--------------------------------------
2023-09-10T17:52:01.325669
Traceback (most recent call last):
  File "/opt/purgeomatic/./delete.movies.unwatched.py", line 89, in <module>
    movies = json.loads(r.text)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

ENV:

```
# Config for all scripts. Defaults are commented out.

RADARR=http://192.168.1.redacted:7878
RADARR_API=redacted

TAUTULLI=http://192.168.1.redacted:8181
TAUTULLI_API=redacted

SONARR=http://192.168.1.redacted:8989
SONARR_API=redacted

#OVERSEERR=http://localhost:5055 # not using it
#OVERSEERR_API=abcdefghijklmnopqrstuvwxyz987654=

TAUTULLI_MOVIE_SECTIONID=10 # yes i checked
TAUTULLI_TV_SECTIONID=11 # this one too

# Number of rows to pull from Tautulli's media table.
TAUTULLI_NUM_ROWS=3000

# Delete movies/series that haven't been watched in this many days.
DAYS_SINCE_LAST_WATCH=730

# For deleting movies/series that have been added, but nobody ever watched.
# Set to 0 to disable.
DAYS_WITHOUT_WATCH=730

# This is off by default! If you set this to any value, it will be on.
# Even the mere existence of this environment variable, set to nothing/blank, and it will be on.
# Turn it on to disable the delete action. The script will only report what it would do.
DRY_RUN=on
```

```
pip install -r requirements.txt
Requirement already satisfied: jq==1.4.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 1)) (1.4.1)
Requirement already satisfied: python-dotenv==1.0.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 2)) (1.0.0)
Requirement already satisfied: requests==2.31.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 3)) (2.31.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.31.0->-r requirements.txt (line 3)) (1.26.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests==2.31.0->-r requirements.txt (line 3)) (3.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.31.0->-r requirements.txt (line 3)) (2020.6.20)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.31.0->-r requirements.txt (line 3)) (2.10)

```
Running this in he same LXC that I run tautulli on.

Any ideas?

**Comment by ASK-ME-ABOUT-LOOM** [comment]
It looks like you're running the Python directly rather than in a container. Perhaps try enclosing all of the values in your .env file in double-quotes (`"`)? Python may be parsing the .env data differently. If this works, I'll need to update the readme. 

As an aside, there's no point to setting DAYS_WITHOUT_WATCH to the same value as DAYS_SINCE_LAST_WATCH. May as well set DAYS_WITHOUT_WATCH to zero and disable it.

**Comment by kysersoze81** [comment]
I'm not running it in docker. I set the dates like that as a precautionary against loosing stuff on the first run.I'll try adding in the quotes and let you know.

**Comment by ASK-ME-ABOUT-LOOM** [comment]
Great! Since I wasn't completely clear, you'll want it to take the form
```
VARIABLE="value"
```

**Comment by kysersoze81** [comment]
Adding the in "" doesn't change the ouput

I've run back through the process and I though I might have found something.
```
:/opt/purgeomatic# make venv
python -m venv .venv
make: python: No such file or directory
make: *** [Makefile:5: venv] Error 127
```

After running the contents of the makefile as python3 it goes through but it doesn't change the result

**Comment by ASK-ME-ABOUT-LOOM** [comment]
After creating the venv with `python3`, you need to switch to the venv and then rebuild the requirements:
```
source .venv/bin/activate
pip install -r requirements.txt
```

Is there a particular reason you're not using the container image? It would solve all of this for you.

**Comment by kysersoze81** [comment]
I did it didn't work.

I use LXC's instead of docker because I don't put all my eggs in 1 basket. I'm not going to run 30 containers in docker because if and when docker falls over all my applications die. Also if i run 1 app per LXC I can restore just the 1 app from a backup or troubleshoot 1 app without interfering with all the others.

**Comment by kysersoze81** [comment]
I've moved my python version up to 3.11.4 as per your docker file 
```
/opt/purgeomatic# python3.11 -m venv .venv
/opt/purgeomatic# source .venv/bin/activate
(.venv) root@Tautulli:/opt/purgeomatic# pip install -r requirements.txt
Requirement already satisfied: jq==1.4.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (1.4.1)
Requirement already satisfied: python-dotenv==1.0.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (1.0.0)
Requirement already satisfied: requests==2.31.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.venv/lib/python3.11/site-packages (from requests==2.31.0->-r requirements.txt (line 3)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.11/site-packages (from requests==2.31.0->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.11/site-packages (from requests==2.31.0->-r requirements.txt (line 3)) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.11/site-packages (from requests==2.31.0->-r requirements.txt (line 3)) (2023.7.22)
--->(.venv) /opt/purgeomatic# python3.11 delete.movies.unwatched.py
--------------------------------------
2023-09-11T18:12:12.649181
Traceback (most recent call last):
  File "/opt/purgeomatic/delete.movies.unwatched.py", line 89, in <module>
    movies = json.loads(r.text)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/opt/purgeomatic# python3.11 ./delete.movies.unwatched.py 
Traceback (most recent call last):
  File "/opt/purgeomatic/./delete.movies.unwatched.py", line 2, in <module>
    import config
  File "/opt/purgeomatic/config.py", line 2, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

```
Still having issues

**Comment by ASK-ME-ABOUT-LOOM** [comment]
At this point we've progressed well beyond my ability to realistically troubleshoot. Something is clearly not working with your python environment, and I wish you good luck in getting that sorted.

**Comment by kysersoze81** [comment]
I'd suggest removing instructions for running the application in another
method if you're not going to support it.
It would also be a good idea to tag the app as docker.

**Comment by ASK-ME-ABOUT-LOOM** [comment]
The assumption would be that anyone choosing to run the python code would have a sufficient measure of experience with Python to deal with irregularities that crop up getting it to work in their own environment. I just wrote the software! I'm not here to troubleshoot a venv.

Further, just because you're using LXC doesn't stop you from using docker to run a one-off container. If you're allergic to docker, use podman. This isn't a docker-exclusive project.

**Comment by kysersoze81** [comment]
Funny if you're so knowledgeable on how to resolve the steps why didn't you
even offer to support it or notice that I was running 3.9 instead of your
3.11.4 alpine

I think your out of your depth and trying to fingerpoint now
I could run it in docker but as I already said docker is not permanent and
it definitely is not the best way to run an environment
Let's not forget. This is your environment running in python that you
apparently cannot support outside of a single docker container

**Comment by ASK-ME-ABOUT-LOOM** [comment]
I say again: best of luck to you.

**Comment by skinner84** [comment]
@kysersoze81 He's made this script on his own and has been good enough to share it with the community. Stop acting like this is something you've paid for. It's best effort, not a production environment.

**Comment by kysersoze81** [comment]
Maybe ask him to publish a link to where the code came from. Even I have
input on that Reddit post.
If you want to be a knob about it why do you offer some insight into what
the issue is
