### ISSUE TITLE
Not an issue: some ideas / feature request

### ISSUE THREAD

**Issue by antipiot** [ASK-ME-ABOUT-LOOM/purgeomatic#5]
Hi!

Thanks for your work, it looks very promising.

I've found your repo while searching for something special:
I use Ombi and i wanted to look for something that may find and delete movie requested by users some times after the download, leaving everything elses "administrator managed" safe.

i think this can be a cool feature!

**Comment by ASK-ME-ABOUT-LOOM** [comment]
Hi, glad you like this! Unless I'm misreading you, this software already does what you're asking for. 🙂 This will delete stuff after it's been downloaded (when people stop watching it) and you can keep content from being deleted with the `protected` file. 

If you're looking for Ombi support to be added, that won't be happening, sorry!
